service: serverless-test-project-alb
frameworkVersion: "3"
configValidationMode: error
variablesResolutionMode: 20210219

plugins:
  - serverless-slic-watch-plugin
package:
  exclude:
    - node_modules/**
    - venv/**
custom:
  resourceTags:
    - Key: ProjectName
      Value: serverless-test-project-alb
    - Key: Stage
      Value: ${self:provider.stage}
  slicWatch:
    # topicArn: ${env:ALARM_TOPIC}
    alarms:
      Lambda:
        Invocations:
          ActionsEnabled: true
          Threshold: 10
      SQS:
        AgeOfOldestMessage:
          Statistic: Maximum
          ActionsEnabled: true
          Threshold: 60
        InFlightMessagesPc:
          Statistic: Maximum
          Threshold: 1 # 1% = 1200 for regular queues or 180 for FIFO queues

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev
  endpointType: REGIONAL

functions:
  albEvent:
    handler: alb-handler.handleALB
    events:
      - alb:
          listenerArn: !Ref httpListener
          priority: 1
          conditions:
            path: /handleALB
            method:
              - POST
          healthCheck: true # it is by default false but can be enbaled true
          #you can disable it for not getting redundant health-check logs on the CloudWatch logs 

resources: ${file(./sls-resources.yml)}
