name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION : "eu-west-1"
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}.x
          cache: 'npm'
      - run: npm ci
      - run: npm test
        name: Run unit tests
      - name: Build TypeScript
        run: npm run build
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.SLIC_WATCH_BUILD_ROLE }}
          role-session-name: github-action-sar-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      - working-directory: ./serverless-test-project
        run: npm test
        name: Run Serverless Framework packaging test
      - working-directory: ./serverless-test-project-alb
        name: Run Serverless Framework packaging test for ALB test project
        run: npm test
      - working-directory: ./serverless-test-project-appsync
        name: Run Serverless Framework packaging test for AppSync test project
        run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-node-${{ matrix.node-version }}
          parallel: true
          path-to-lcov: .tap/report/lcov.info
        if: ${{ always() }}

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
          path-to-lcov: .tap/report/lcov.info
